# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-28 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20190813_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=128, unique=True, verbose_name='主机唯一ID'),
        ),
    ]
