# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20191028_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='user',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='使用人'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cabinet_order',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='U位'),
        ),
    ]
